/* Fictional, standalone design lab. No production data, APIs or persistence. */
'use strict';
const app=document.querySelector('#app'),dialog=document.querySelector('#details'),content=document.querySelector('#dialog-content');
const params=new URLSearchParams(location.search);
const state={theme:'arcade',screen:'play',role:'owner',game:'complete',sound:false,person:'Jennifer',common:true,metric:'Win rate',period:'All time',player:'Logan',count:10,search:'',selected:[],solved:[],guesses:[],misses:0,busy:false};
const cats=[['p','WORDS BEFORE “BOARD”',['CLIP','CUP','KEY','SKATE']],['y','FRUITS',['APPLE','BANANA','GRAPE','PEACH']],['g','WAYS TO MOVE QUICKLY',['BOLT','DASH','RACE','SPRINT']],['b','PARTS OF A BOOK',['COVER','INDEX','PAGE','SPINE']]];
const players=['Logan','Jennifer','Mom','ANP'];
const records=Object.fromEntries(players.map((p,j)=>[p,Array.from({length:24},(_,i)=>({id:j+'-'+i,n:1276-i,day:28-i,m:i===0&&j===0?0:(i+j)%5}))]));

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,action,extra='')=>`<button class="button ${extra}" data-action="${action}">${text}</button>`;
const grid=(mini=false,m=0)=>`<div class="result-grid ${mini?'mini':''}" aria-label="Result grid">${(Array.from({length:m},()=> 'pybg').join('')+(m===4?'yyyygggg':'ppppyyyyggggbbbb')).split('').map(c=>`<i class="${c}"></i>`).join('')}</div>`;
function head(name,sub){return `<header class="app-header"><div><span class="eyebrow">${sub||'A little friendly competition'}</span><h1>${name}</h1></div><span class="edition" aria-hidden="true"><i></i><i></i><i></i><i></i></span></header>`;}
function nav(){return `<nav class="bottom" aria-label="Main navigation" style="grid-template-columns:repeat(${state.role==='owner'?4:3},1fr)">${[['play','Play','◇'],['stats','Stats','▥'],['history','History','↶'],...(state.role==='owner'?[['admin','Admin','⚙']]:[])].map(([k,t,i])=>`<button class="nav-item ${state.screen===k||k==='stats'&&['compare'].includes(state.screen)?'active':''}" data-go="${k}"><span aria-hidden="true">${i}</span>${t}</button>`).join('')}</nav>`;}
function tabs(){return `<div class="tabs">${[['stats','My Stats'],['compare','Head-to-Head']].map(([k,t])=>`<button data-go="${k}" aria-pressed="${state.screen===k}" class="${state.screen===k?'active':''}">${t}</button>`).join('')}</div>`;}
function solveTrail(){const order=state.guesses.length?state.solved:['p','y','g','b'];const names={p:'Purple',y:'Yellow',g:'Green',b:'Blue'};return `<section class="solve-trail"><span class="trail-label">Your solve order</span><div class="trail-steps">${order.length?order.map((c,i)=>`<div class="trail-step"><span class="trail-tile ${c}" style="--step:${i}">${i+1}</span><small>${names[c]}</small></div>`).join(''):'<p>No groups solved</p>'}</div></section>`;}
function today(){if(state.game!=='complete')return `<section class="panel empty-summary"><span class="eyebrow">Today’s summary</span><h2>${state.game==='playing'?'Your next move awaits.':'A fresh puzzle. Your move.'}</h2><p>There’s a spot on the board with your name on it.</p>${btn(state.game==='playing'?'Continue playing':'Go play today’s puzzle','start','primary')}</section>`;let m=state.misses;return `<section class="panel summary"><div class="summary-head"><span class="eyebrow">Today’s summary</span><small>#1276</small></div><div class="summary-core"><div class="result-copy"><span class="result-icon">${m?'✦':'★'}</span><h2>${m===4?'A tricky one.':m?'Nicely solved.':'Perfect game!'}</h2><p>${m?'Your original result is recorded.':'Four connections. No wrong turns.'}</p></div>${state.guesses.length?`<div class="result-grid" aria-label="Your sample guesses">${state.guesses.flatMap(g=>g.map(w=>`<i class="${cats.find(c=>c[2].includes(w))[0]}"></i>`)).join('')}</div>`:grid(false,m)}</div><div class="achievement-row"><span class="badge gold">${m===4?state.solved.length+' groups found':m?m+' mistakes':'★ Flawless'}</span></div><div class="daily-metrics"><div><strong>${m}</strong><small>Mistakes</small></div><div><strong>${state.guesses.length?state.solved.length:4}</strong><small>Groups found</small></div><div><strong>13</strong><small>Day streak</small></div></div>${solveTrail()}${btn('↗ Share result','share','primary full')}</section>`;}
function bars(){return `<section class="solved">${(state.game==='complete'?cats:cats.filter(c=>state.solved.includes(c[0]))).map(([c,t,w])=>`<div class="solved-bar ${c}"><strong>${t}</strong><span>${w.join(', ')}</span></div>`).join('')}</section>`;}
function play(){let h=head('Connections','Your daily little victory')+`<div class="context-line"><span>Puzzle #1276</span><span>Sample puzzle</span></div>`;if(state.game==='complete')return h+bars()+`<div class="previous">${btn('↶ Previous guesses','guesses','quiet')}</div>`+today()+`<div class="motion-helper">${btn('Try the board & animations','start','quiet')}</div>`;if(state.game==='unplayed')return h+today();return h+bars()+`<p class="board-status" role="status">Create four groups of four.</p><div class="board">${Array.from({length:16},(_,i)=>cats[i%4][2][Math.floor(i/4)]).filter(w=>!cats.some(c=>state.solved.includes(c[0])&&c[2].includes(w))).map(w=>`<button class="tile ${state.selected.includes(w)?'selected':''}" data-word="${w}" aria-pressed="${state.selected.includes(w)}">${w}</button>`).join('')}</div><div class="mistakes">Mistakes remaining ${Array.from({length:4},(_,i)=>`<i class="${i<state.misses?'used':''}"></i>`).join('')}</div><div class="board-tools">${btn('Deselect','deselect','quiet')}${btn('Submit','submit','primary')}</div><div class="motion-helper">${btn('Show me a correct match','demo','quiet')}<p>Fictional puzzle · nothing is saved</p></div>`;}
function stats(){return head('Stats','Logan · Your story so far')+tabs()+today()+`<div class="section-head"><h2>All-time highlights</h2><small>124 games</small></div><div class="stat-grid">${[['◎','Win rate','93%'],['★','Perfect games','42'],['↯','Best streak','18'],['⊙','Avg. mistakes','2.1'],['◇','Purple first','38'],['◇','Games played','124']].map(([i,l,v])=>`<div class="stat"><span class="stat-symbol">${i}</span><strong>${v}</strong><small>${l}</small></div>`).join('')}</div><div class="section-head"><h2>Which color comes first?</h2></div><div class="first-colors">${[['p','Purple',38],['y','Yellow',35],['g','Green',30],['b','Blue',21]].map(([c,name,v])=>`<div class="first-color ${c}"><span class="color-caption">${name}</span><strong>${v}</strong><small>first solves</small><div class="mini-squares" aria-hidden="true">${'<i></i>'.repeat(4)}</div></div>`).join('')}</div><div class="section-head"><h2>Last ten games</h2></div><div class="performance">${[1,1,1,0,1,1,1,1,1,1].map(v=>`<i class="${v?'':'loss'}">${v?'✓':'×'}</i>`).join('')}</div>`;}
function compare(){const group=['Selected group','Everyone'].includes(state.person),n=state.common?38:124,them=state.person==='Mom'?88:group?90:94;return head('Stats','A fair little rivalry')+tabs()+`<section class="panel"><label class="field-label" for="opponent">Compare yourself with</label><select class="select" id="opponent">${['Jennifer','Mom','ANP','Selected group','Everyone'].map(p=>`<option ${p===state.person?'selected':''}>${p}</option>`).join('')}</select>${state.person==='Selected group'?'<p class="footnote">Sample group: Jennifer + Mom</p>':''}<div class="duel"><div><span class="name">Logan · You</span><strong class="big">${state.common?92:93}%</strong><small>Win rate</small></div><span class="vs">vs</span><div><span class="name">${group?'Group average':state.person}</span><strong class="big">${them}%</strong><small>Win rate</small></div></div><div class="segment"><button data-mode="all" class="${!state.common?'active':''}">All results</button><button data-mode="common" class="${state.common?'active':''}">Games in common</button></div><p class="footnote">${state.common?n+' shared puzzles · matching puzzle IDs only':'Each player’s full recorded history'}</p>${[['1.8','Avg. mistakes','2.1'],['29%','Perfect rate','26%'],['31%','Purple first','28%']].map(([a,l,b])=>`<div class="comparison-row"><strong class="best">${a}</strong><span>${l}</span><strong>${b}</strong></div>`).join('')}</section><p class="footnote">Illustrative comparisons. Group figures are averages, not combined totals.</p>`;}
function historyPage(){const list=records[state.player].filter(r=>String(r.n).includes(state.search));return head('History','The games that got you here')+(state.role==='owner'?`<label class="field-label" for="history-player">Player</label><select id="history-player" class="select">${players.map(p=>`<option ${p===state.player?'selected':''}>${p}</option>`).join('')}</select>`:'')+`<input class="search" id="search" type="search" placeholder="Search puzzle number" aria-label="Search puzzle number" value="${esc(state.search)}"><div class="section-head"><h2>${state.player}’s games</h2><small>${list.length} results</small></div><section class="panel">${list.slice(0,state.count).map(r=>`<button class="history-row" data-record="${r.id}"><span class="day">AUG<strong>${r.day}</strong></span><span class="history-copy"><strong>${r.m===0?'Perfect':r.m===4?'Unsolved':'Solved'}</strong><small>#${r.n} · ${r.m} mistakes</small></span>${grid(true,r.m)}<span>›</span></button>`).join('')||'<p>No matching games.</p>'}</section>${state.count<list.length?btn('Load 10 more','more','full'):''}`;}
function admin(){return head('Admin','Only you · Preview controls')+`<section class="panel">${[['↗','Import results','Paste a result for any player'],['♙','Manage players','Names and account access'],['⚙','Game tools','Owner controls and testing'],['◇','Preferences','Sound, motion, and appearance']].map(([i,t,s])=>`<button class="admin-item" data-admin="${t}"><span class="admin-symbol">${i}</span><span class="admin-copy"><strong>${t}</strong><small>${s}</small></span><span>›</span></button>`).join('')}</section><p class="footnote">Public design preview only. Owner/member views are simulated; no live controls are connected.</p>`;}
function render(){document.body.dataset.theme=state.theme;document.querySelectorAll('[data-theme-choice]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.themeChoice===state.theme));if(state.role!=='owner'&&state.screen==='admin')state.screen='play';app.innerHTML=({play,stats,compare,history:historyPage,admin}[state.screen]||play)()+nav();}
function show(t,h){document.querySelector('#dialog-title').textContent=t;content.innerHTML=h;if(!dialog.open)dialog.showModal();}
function notify(t){const n=document.querySelector('#notice');n.textContent=t;n.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>n.hidden=true,3000);}
function tone(){if(!state.sound)return;try{const ctx=tone.ctx||(tone.ctx=new(window.AudioContext||window.webkitAudioContext)());ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.setValueAtTime(523,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(784,ctx.currentTime+.12);g.gain.setValueAtTime(.04,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);o.start();o.stop(ctx.currentTime+.2);}catch{}}
function start(){state.game='playing';state.solved=[];state.selected=[];state.guesses=[];state.misses=0;state.screen='play';document.querySelector('#game-state').value='playing';render();}
async function submit(){if(state.busy||state.selected.length!==4){notify('Select four words first');return;}state.guesses.push([...state.selected]);const c=cats.find(c=>state.selected.every(w=>c[2].includes(w)));if(!c){state.misses++;state.selected=[];if(state.misses===4){state.game='complete';document.querySelector('#game-state').value='complete';}render();notify(state.misses===4?'Sample game ended. Nothing saved.':'Not a group — try another connection.');return;}state.busy=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const tiles=[...app.querySelectorAll('.tile')],board=app.querySelector('.board').getBoundingClientRect();const selected=tiles.filter(t=>state.selected.includes(t.dataset.word));await Promise.all(selected.map((t,i)=>{const r=t.getBoundingClientRect();return t.animate([{transform:'translate(0,0)'},{transform:`translate(${board.left+i*(r.width+7)-r.left}px,${board.top-r.top}px)`}],{duration:reduced?0:450,easing:'cubic-bezier(.22,1,.36,1)',fill:'forwards'}).finished;}));const old=new Map(tiles.map(t=>[t.dataset.word,t.getBoundingClientRect()]));state.solved.push(c[0]);state.selected=[];if(state.solved.length===4){state.game='complete';document.querySelector('#game-state').value='complete';}render();app.querySelectorAll('.tile').forEach(t=>{const a=old.get(t.dataset.word),b=t.getBoundingClientRect();if(a)t.animate([{transform:`translate(${a.left-b.left}px,${a.top-b.top}px)`},{transform:'none'}],{duration:reduced?0:380,easing:'cubic-bezier(.22,1,.36,1)'});});const bar=app.querySelector('.solved-bar:last-child');if(bar)bar.animate([{opacity:.4,transform:'scale(.96)'},{opacity:1,transform:'scale(1)'}],{duration:reduced?0:300});tone();state.busy=false;}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||state.busy)return;if(b.dataset.go){state.screen=b.dataset.go;render();scrollTo(0,0);return;}if(b.dataset.word){const w=b.dataset.word;if(state.selected.includes(w))state.selected=state.selected.filter(x=>x!==w);else if(state.selected.length<4)state.selected.push(w);render();return;}if(b.dataset.mode){state.common=b.dataset.mode==='common';render();return;}if(b.dataset.period){state.period=b.dataset.period;render();return;}if(b.dataset.record){const r=records[state.player].find(r=>r.id===b.dataset.record);show('Puzzle #'+r.n,`<p>${state.player} · ${r.m} mistakes</p>${grid(false,r.m)}<p>Expanded game details will be designed later.</p>${state.role==='owner'?`<button class="button" data-delete="${r.id}">Delete sample result</button><p class="footnote">Only removes this fictional result until reload.</p>`:''}`);return;}if(b.dataset.admin){show(b.dataset.admin,b.dataset.admin==='Import results'?'<p>Owner-only. Sample preview; nothing is saved.</p><textarea placeholder="Paste a sample result" aria-label="Sample import"></textarea><button class="button" data-import>Preview sample</button>':'<p>Design placeholder. No real accounts or game data are connected.</p>');return;}switch(b.dataset.action){case'start':start();break;case'deselect':state.selected=[];render();break;case'submit':submit();break;case'demo':state.selected=[...cats.find(c=>!state.solved.includes(c[0]))[2]];render();submit();break;case'more':state.count+=10;render();break;case'guesses':show('Previous guesses',state.guesses.length?state.guesses.map((g,i)=>`<div class="guess-row" style="background:var(--raised);color:var(--text)"><strong>Guess ${i+1}</strong><p>${g.join(', ')}</p></div>`).join(''):cats.map(([c,t,w],i)=>`<div class="guess-row ${c}"><strong>${i+1}. ${t}</strong><p>${w.join(', ')}</p></div>`).join(''));break;case'share':show('Share sample result','<p>Fictional design-preview result.</p><textarea readonly aria-label="Share text">Connections — sample puzzle #1276\n🟪🟪🟪🟪\n🟨🟨🟨🟨\n🟩🟩🟩🟩\n🟦🟦🟦🟦</textarea><button class="button" data-copy>Copy result</button>');break;}});
app.addEventListener('change',e=>{if(e.target.id==='opponent')state.person=e.target.value;if(e.target.id==='metric')state.metric=e.target.value;if(e.target.id==='history-player'){state.player=e.target.value;state.count=10;}render();});
app.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;state.search=e.target.value;render();const s=document.querySelector('#search');s.focus();try{s.setSelectionRange(pos,pos);}catch{}}});
document.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>{if(state.busy)return;state.theme=b.dataset.themeChoice;const u=new URL(location.href);u.searchParams.set('theme',state.theme);window.history.replaceState({},'',u);render();}));
document.querySelector('#role').onchange=e=>{state.role=e.target.value;state.player='Logan';state.screen='play';dialog.close();render();};
document.querySelector('#game-state').onchange=e=>{if(state.busy)return;if(e.target.value==='playing')start();else{state.game=e.target.value;state.misses=0;state.guesses=[];state.solved=[];state.screen='play';render();}};
document.querySelector('#sound').onclick=e=>{state.sound=!state.sound;e.target.textContent=state.sound?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',state.sound);tone();};
document.querySelector('#close-dialog').onclick=()=>dialog.close();
content.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-copy')){try{await navigator.clipboard.writeText(content.querySelector('textarea').value);notify('Copied sample result');}catch{content.querySelector('textarea').select();notify('Select and copy the text');}}if(b.dataset.delete&&state.role==='owner'){records[state.player]=records[state.player].filter(r=>r.id!==b.dataset.delete);dialog.close();render();}if(b.hasAttribute('data-import')){show('Sample import preview',`<p>Not saved.</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(content.querySelector('textarea').value)}</pre>`);}});
render();
